### PR TITLE
new problems for trig substitution

### PR DESCRIPTION
**Pull request by mathriddle**
8 problems for section 6.4

(I tried to upload and replace a file in section 6.2 (Integration by parts) where I cleaned up some formatting issues, but that didn't seem to work even though a "commit" is shown. I don't use GitHub enough to remember all the steps.)

### CODE REVIEW

**Comment by mathriddle** [comment]
Added 5 additional problems for section 6.5 on partial fractions. All of these use scaffording where students have to do the partial fraction decomposition correctly in part 1 before part 2 will open to do the actual antidifferentiation.

**Comment by sean-fitzpatrick** [comment]
Thanks for this pull request! I've just returned from vacation today; sorry if it looked like I was ignoring it.

I'll try to look this over very soon.

**Comment by sean-fitzpatrick** [comment]
These look good! (I haven't tested, but I see PGML, TikZ, and scaffolding -- there always seem to be too few modern problems in the OPL.)

Are you planning any further commits? If so I'll leave this open. If you're done, I'll merge.

**Comment by mathriddle** [comment]
Cleaned up some formatting issues in all the problems in the section for integration by parts to make the integration by parts data tables and the integrals a bit easier to read and more consistent in format.

**Comment by mathriddle** [comment]
Just added to the commit to include changes to the problems in integration
by parts to clean up the formatting in the integration by parts data tables
and in the integrals, and to make the formatting more consistent within and
across all the problems.

**Comment by mathriddle** [comment]
oops, I meant added to the pull request.... At least I hope that is what I
did. Let me know if you see those changes to the integration by parts
section

**Comment by sean-fitzpatrick** [comment]
Yes, I can see the changes, thanks!

**Comment by sean-fitzpatrick** [comment]
@mathriddle let me know if you want to push any further changes here. Otherwise, I'll merge this tomorrow. (At which point you would need to open a new pull request.)

**Comment by mathriddle** [comment]
No more changes for now, so you can go ahead with the merge. Thanks.

**Comment by sean-fitzpatrick** [comment]
Thank you for the new problems!

**Pull request merged**
